config/routes.rb
Rails.application.routes.draw do
  
  root 'template#index'
  
  get 'index' => 'template#index'
  get 'favorites' => 'template#favorites'
  get 'submit' => 'template#submit'
  
  get 'articles' => 'template#articles'
  get 'essays' => 'template#essays'
  
  # sample article pages
  get 'article' => 'template#article'
  get 'remarkable' => 'template#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

def html_open_tag
    ('<html lang="en"' + (cookies[:fontsLoaded] ? ' class="fonts-loaded"'.html_safe : '') + '>').html_safe
end

app/controllers/counter_controller.rb
class CounterController < ApplicationController
  def index
  end
end

app/controllers/template_controller.rb
class TemplateController < ApplicationController
  def Article
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
  def inline_file(path)
    if assets = Rails.application.assets
      asset = assets.find_asset(path)
      return '' unless asset
      asset.source
    else
      File.read(File.join(Rails.root, 'public', asset_path(path)))
    end
  end

  def inline_js(path)
    "<script>#{inline_file path}</script>".html_safe
  end

  def inline_css(path)
    "<style>#{inline_file path}</style>".html_safe
  end
end

app/helpers/template_helper.rb
module TemplateHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#ed236e">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Analog.Cafe">
<meta name="application-name" content="Analog.Cafe">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= html_open_tag %>
  <head>
  	<meta charset="utf-8">
    <title>Analog.Cafe &#x2615; <%= @document_title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= csrf_meta_tags %>
    <%= inline_css 'fonts/loader' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= inline_js 'dcl/dcl' %>
    <%= javascript_include_tag 'application', async: Rails.env.production? %>
    <%= render 'application/favicon' %>
  </head>

  <body data-controller-action="<%= controller.action_name  %>">
		<%= render "shared/nav" %>
  	<main>
    	<%= yield %>
    </main>
  </body>
</html>

app/views/samples/article.html.erb
<% @title="Article" %>

<article>
	<header>
		<h1>The Misty Adventures</h1>
		<span class="subtitle">A drive through the misty mountains of Northern Thailand</span>
		<span class="small-caption">Written by <a href="#">dmitrizzle</a> on January 12, 2017</span>
		<a href="#" class="favorite"><%= inline_svg "components/button-favorite--empty.svg", desc: "Favorite button" %><%= inline_svg "components/button-favorite--filled.svg", desc: "Favorite button" %></a>
	</header>
	<section>
		<figure class="feature">
			<%= image_tag "samples/11.6.2016-de.jpg" %>
			<figcaption>This is not a pipe" is a famous play on reality by René Magritte. He was trying to say that the image he drew and most would refer to as a "pipe" isn't. It's just a drawing or a collection of color pigments on a piece of paper. Can't smoke that.</figcaption>
		</figure>
		<p>The things that we see go beyond being merely projected onto the back of our eyes. It all has to go somewhere. Before we even get to react to the images a part of our brain turns everything into a visual story that has a meaning. Without this crucial process, humans <a href="https://en.wikipedia.org/wiki/Visual_agnosia#Symptoms">would not be able to</a> distinguish between a child and a fire hydrant. Even the simplest things like lines and squares would not exist unless the brain can find them in the matrix of dots that our eyes transmit...</p>
		<h2>Second-level heading</h2>
		<p>Before I got involved with making websites and even photography animation was my primary method of expression. Back in the 90's my elementary school friends and I got pirated copies of 3D Studio MAX to play with. Back then computers were a novelty so just seeing things move on a screen was cool as fuck. Everything we created was obviously garbage but this process started an itch. An itch to create and experiment that made me the man I am today.</p>
		<figure>
			<img alt="This is not a pipe." src="https://www.artsocket.com/images/art/L_Woop-Woop.jpg">
			<figcaption>"This is not a pipe" is a famous play on reality by <a href="https://en.wikipedia.org/wiki/The_Treachery_of_Images">René Magritte</a>. He was trying to say that the image he drew and most would refer to as a "pipe" isn't. It's just a drawing or a collection of color pigments on a piece of paper. Can't smoke that.</figcaption>
		</figure>
		
		<h3>Third-level heading</h3>
		<p>A few years later I had to leave everything, everyone, behind to move with my family from Russia to Canada. My hobbies varied considerably since the days of playing with ancient software. Most of the time I just wanted to speak and understand proper English and fit in somehow. Later I decided that I wanted to pick up chicks, so skateboarding and electric guitars took over.</p>
		<p>Life isn't static. Neither is our perception of it. Motion, just like the objects (which are dots before they become things) has to be understood. If we fail, we can no longer live a healthy life as everything turns into a slideshow. The horrors of an old computer and a demanding video game become a reality.</p>
		<aside class="card-embed">
			<figure>
				<img src="https://pbs.twimg.com/media/C1Y2wyIUoAAZAw9.jpg:large">
				<figcaption><a href="#">@analog_cafe</a>: "The meaning of life is to find your gift. The purpose of life is to give it away.”  ― Pablo Picasso</figcaption>
			</figure>
			<a href="#" class="button">View on Twitter</a>
		</aside>
		<p>Most of the time things work just fine. We see stuff, the brain makes sense out of it; how it moves and changes over time. Occasionally, nothing is there, neither does it move. A video that you watch on YouTube isn't real. It's just millions of tiny light bulbs changing color as dictated by the computer. Everything is static, except for the intensity of light and the wavelength for each pixel.</p>
		<p>We think something is in motion when it changes ten times per second or faster. What happens to it within each one of those moments is crucial as it adds to our idea of where it moves or how it changes.</p>
		<p>The irst time we tricked our brains like that was over <a href="https://en.wikipedia.org/wiki/History_of_animation#Early_approaches_to_motion_in_art">5,000 years ago</a>. We never stopped since. Animation has been with us through time as we told stories and brought them to life through sound, written word, and images.</p>
		<figure class="feature">
			<img src="https://www.artsocket.com/images/art/L_Very-Red-Flower.jpg">
			<figcaption>This is not a pipe" is a famous play on reality by René Magritte. He was trying to say that the image he drew and most would refer to as a "pipe" isn't. It's just a drawing or a collection of color pigments on a piece of paper. Can't smoke that.</figcaption>
		</figure>
		<aside class="card">
			<header>
				<h3>Section Card</h3>
				<a href="#">&#10005;</a>
			</header>
			<figure>
				<img src="https://www.artsocket.com/images/art/L_Let-It-Go.jpg">
				<figcaption>This is a card. It contains additional info, options & contextual menus.</figcaption>
			</figure>
			<a href="#" class="button">Section Card Button</a>
		</aside>
		<a href="#" class="button">Section Button</a>
	</section>
	<a href="#" class="button">Article Button</a>
</article>
<a href="#" class="button">Main Button</a>
<aside class="card" style="position: absolute; z-index: 2; top: 1040px; left: calc(50% - 160px);">
	<header>
		<h3>Main Card</h3>
		<a href="#">&#10005;</a>
	</header>
	<figure>
		<img src="https://www.artsocket.com/images/art/L_Let-It-Go.jpg">
		<figcaption>This is a card. It contains additional info, options & contextual menus.</figcaption>
	</figure>
	<a href="#" class="button">Main Card Button</a>
</aside>

app/views/shared/_nav.html.erb
<nav>
	<ul>
		<li><%= link_to articles_path, class: 'button-articles' do %><span>Articles</span><% end %></li>
		<li><%= link_to essays_path, class: 'button-essays' do %><span>Photo Essays</span><% end %></li>
		<li class="nav-center">
			<div class="logo-container button-index">
				<h1 title="Analog.Cafe">
					<span>A</span>
					<span>n</span>
					<span>a</span>
					<span>l</span>
					<span>o</span>
					<span>g</span>
					<span>.</span>
					<span>C</span>
					<span>a</span>
					<span>f</span>
					<span>e</span>
				</h1>
				<%= link_to index_path, class: 'button' do inline_svg "branding/logo-lettering.svg", class: "logo", desc: "Analog.Cafe logo" end %>
			</div>
		</li>
		<li class="nav-important--left"><%= link_to favorites_path, class: 'button-favorites' do %><span data-label--prepend="My ">Favorites</span><% end %></li>
		<li class="nav-important--right"><%= link_to submit_path, class: 'button-submit' do %><span>Submit</span><% end %></li>
	</ul>
</nav>

app/views/shared/_table-of-contents.html.erb
<!-- LIST -->
<ul class="table-of-contents">
	
	<!-- LOAD BLOCK -->
	<li>
		<a href="/article">
			<section class="toc-summary">
				<figure><%= image_tag "template/green.jpg" %></figure>
				<h2>Why Shoot Film?</h2>
				<p class="toc-chartrim">I bought my first film camera five years ago as a 17th birthday present to myself. I saved up my money and walked to a little old and dusty Kodak shop and bought myself a Nikkormat FT2 with a 50mm lens.</p>
				<div class="toc-info"><span>Photo Essay | 8 Images</span><em>Kayla Medica &middot; January 12, 2017</em></div>
			</section>
			<figure class="toc-cover" style="background-image:url(<%= asset_path('template/green.jpg') %>);"></figure>
		</a>
	</li>
	<li>
		<a href="/article">
			<section class="toc-summary">
				<figure><%= image_tag "template/graphic.jpg" %></figure>
				<h2>The Science of Analog Pho&shy;to&shy;graphy</h2>
				<p class="toc-chartrim">Analog Pho&shy;to&shy;graphy is the method and the tools popular amongst amateur and professional photographers up until the early 2000s. Today it is still used by millions of artists and hobbyists who appreciate or feel fascinated by the process and the results.</p>
				<div class="toc-info"><span>Article | 7-minute read</span><em>dmitrizzle &middot; January 12, 2017</em></div>
			</section>
			<figure class="toc-cover" style="background-image:url(<%= asset_path('template/graphic.jpg') %>);"></figure>
		</a>
	</li>
	<li>
		<a href="/article">
			<section class="toc-summary">
				<figure><%= image_tag "template/angles.jpg" %></figure>
				<h2>Angles</h2>
				<p class="toc-chartrim"></p>
				<div class="toc-info"><span>Featured Photo</span><em>Robert Davie &middot; January 12, 2017</em></div>
			</section>
			<figure class="toc-cover" style="background-image:url(<%= asset_path('template/angles.jpg') %>);"></figure>
		</a>
	</li>
	<li>
		<a href="/article">
			<section class="toc-summary">
				<figure><%= image_tag "template/L_Woop-Woop.jpg" %></figure>
				<h2>Full City</h2>
				<p class="toc-chartrim">Over the past couple of years I have received an enormous amount of submissions for artwork, Pho&shy;to&shy;graphy and written word. This willingness to trust the “creative labor of love” into my team’s hands is very flattering and gratifying.</p>
				<div class="toc-info"><span>Photo Essay | 9 Images</span><em>dmitrizzle &middot; January 12, 2017</em></div>
			</section>
			<figure class="toc-cover" style="background-image:url(<%= asset_path('template/L_Woop-Woop.jpg') %>);"></figure>
		</a>
	</li>
	<li>
		<a href="/article">
			<section class="toc-summary">
				<figure><%= image_tag "template/Analog.Cafe-Poster.jpg" %></figure>
				<h2>My vision for Analog.Cafe</h2>
				<p class="toc-chartrim">For the past decade, I’ve been working on developing creative communities online. I haven’t realized that until today.</p>
				<div class="toc-info"><span>Article | 2-minute read</span><em>dmitrizzle &middot; January 12, 2017</em></div>	
			</section>
			<figure class="toc-cover" style="background-image:url(<%= asset_path('template/Analog.Cafe-Poster.jpg') %>);"></figure>
		</a>
	</li>
	<li>
		<a href="/article">
			<section class="toc-summary">
				<figure><%= image_tag "template/beach.jpg" %></figure>
				<h2>Brighton Beach</h2>
				<p class="toc-chartrim">Brighton Beach is a Russian community neighbourhood in New York. When I was growing up in Moscow as a kid I’ve heard a lot about it on TV: the magical place where one can become and live like an American.</p>
				<div class="toc-info"><span>Photo Essay | 5 Images</span><em>Lee Clark &middot; January 12, 2017</em></div>
			</section>
			<figure class="toc-cover" style="background-image:url(<%= asset_path('template/beach.jpg') %>);"></figure>
		</a>
	</li>
	<li>
		<a href="/article">
			<section class="toc-summary">
				<figure><%= image_tag "template/11.6.2016-de.jpg" %></figure>
				<h2>The Weekly Robot #1</h2>
				<p class="toc-chartrim">Every day our friendly robot spends her time looking at analog photographs on Twitter and beyond. Her decisions are based on logic, crafted by humans who love film. Her job is to post the most interesting find, here, every Saturday. Her name is Roberta &#x1F916;</p>
				<div class="toc-info"><span>Shared | 1 Link</span><em>Roberta The Robot &middot; January 12, 2017</em></div>
			</section>
			<figure class="toc-cover" style="background-image:url(<%= asset_path('template/11.6.2016-de.jpg') %>);"></figure>
		</a>
	</li>
	<li class="feature">
		<a href="/article">
			<section class="toc-summary">
				<figure><%= image_tag "template/L_Let-It-Go.jpg" %></figure>
				<h2>Let it Go</h2>
				<p class="toc-chartrim">My first cross-processed long exposure shot. Being an experimental film technique there is a lot of potential for both serendipity and failiure. And as a newbie I couldn't even imagine what it would look like once the strip has left the chemical bath at a photo lab.</p>
				<div class="toc-info"><span>Photo Essay | 5 Images</span><em>Chi &middot; January 12, 2017</em></div>
			</section>
			<figure class="toc-cover" style="background-image:url(<%= asset_path('template/L_Let-It-Go.jpg') %>);"></figure>
		</a>
	</li>
	<!-- END LOAD BLOCK -->	
	
</ul>
<!-- END LIST -->

<!--
	What is a load block?
	Top of the page:
		- 1 (top) list item overflows header
		- 5 list items
		- 1 feature (only for default, non-sorted/non-filtered view)
	Next:
		- 10 list items
	Next:
		- 10 list items
	...
	First post ever (last post in this list):
		- feature (only for default, non-sorted/non-filtered view)
		- "Load More..." toc-info becomes "Submit Your..."
	
	How is feature defined?
		- Set by editor/owner, expires after 3 days
		- If expired/none, 7th post from the top (chronologically)
		
		
	TEXT FILTERS:
	Note the "Pho&shy;to&shy;graphy" that replaces "Photography" - this is to help with browser hyphenation and should be applied to all of the words output into HTML on Analog.Cafe
-->

app/views/template/about.html.erb
<% @document_title="The Remarkable" %>

<article>
	<header>
		<h1>The Remarkable Photo Blog</h1>
		<span class="subtitle">About Analog.Cafe</span>
	</header>
	<section>
		<figure class="feature"><%= image_tag "template/grainy-camera.jpg" %><figcaption>Film grain. Dust and scratches. Unexpected results. The dark magic of film shines on Analog.Cafe.</figcaption></figure>
		<h2>For The Creators:</h2>
		<p>Analog.Cafe is more than just a blog. It is the <strong>ultimate publishing platform for the film photography community</strong>.</p>
		<p>Anyone can submit images, photo essays and articles through the beautiful, easy to use web app. No more complicated, ugly forms. <em>Analog Cafe</em> is a publication by the film photography community &mdash; for everyone.</p>
		<p>Featured images are listed in a special database. From there they can be re-published by other contributors in their articles or essays. This gives more exposure to the original photographer and facilitates <strong>effortless collaboration</strong>.</p>
		<p>Every submission goes through a careful editorial process. Together, we build a remarkable and lasting experience for thousands of visitors from around the world.</p>
		<blockquote><p>Anyone can submit images, photo essays and articles through the beautiful, easy to use web app. Featured images are listed in a special database. From there they can be re-published by others. This... facilitates <strong>effortless collaboration</strong>.</p></blockquote>
		<h2>For everyone:</h2>
		<p><em>Analog.Cafe</em> is a collection of images, articles and photo essays. It is a fully curated and edited body of work that draws on the best and most interesting expressions from the film photography community and beyond.</p>
		<p>The best way to really understand <em>Analog.Cafe</em> is to start discovering the work created by its members. Now is a good time:</p>
		<%= link_to index_path, class: 'button' do %>Start Here &#x1F64C;<% end %>
</article>

app/views/template/article.html.erb
<% @document_title="Article" %>

<article>
	<header>
		<h1>My Vision for Analog.Cafe</h1>
		<span class="subtitle">A new project, for and by the film photography community</span>
		<span class="small-caption">Written by <a href="#">dmitrizzle</a> &middot; January 30, 2017</span>
		<div class="controls"><a href="#" class="favorite"></a></div>
	</header>
	<section>
		<figure class="feature">
			<%= image_tag "template/Analog.Cafe-Poster.jpg" %>
			<figcaption>Image credit: “Federal Rhine” by Betty.</figcaption>
		</figure>
		<p>The things that we see go beyond being merely projected onto the back of our eyes. It all has to go somewhere. Before we even get to react to the images a part of our brain turns everything into a visual story that has a meaning. Without this crucial process, humans <a href="https://en.wikipedia.org/wiki/Visual_agnosia#Symptoms">would not be able to</a> distinguish between a child and a fire hydrant. Even the simplest things like lines and squares would not exist unless the brain can find them in the matrix of dots that our eyes transmit...</p>
		<h2>Second-level heading</h2>
		<p>Before I got involved with making websites and even photography animation was my primary method of expression. Back in the 90's my elementary school friends and I got pirated copies of 3D Studio MAX to play with. Back then computers were a novelty so just seeing things move on a screen was cool as fuck. Everything we created was obviously garbage but this process started an itch. An itch to create and experiment that made me the man I am today.</p>
		<figure>
			<%= image_tag "template/L_Woop-Woop.jpg" %>
			<figcaption>"This is not a pipe" is a famous play on reality by <a href="https://en.wikipedia.org/wiki/The_Treachery_of_Images">René Magritte</a>. He was trying to say that the image he drew and most would refer to as a "pipe" isn't. It's just a drawing or a collection of color pigments on a piece of paper. Can't smoke that.</figcaption>
		</figure>
		
		<h3>Third-level heading</h3>
		<p>A few years later I had to leave everything, everyone, behind to move with my family from Russia to Canada. My hobbies varied considerably since the days of playing with ancient software. Most of the time I just wanted to speak and understand proper English and fit in somehow. Later I decided that I wanted to pick up chicks, so skateboarding and electric guitars took over.</p>
		<p>Life isn't static. Neither is our perception of it. Motion, just like the objects (which are dots before they become things) has to be understood. If we fail, we can no longer live a healthy life as everything turns into a slideshow. The horrors of an old computer and a demanding video game become a reality.</p>
		<aside class="card-embed">
			<figure>
				<img src="https://pbs.twimg.com/media/C1Y2wyIUoAAZAw9.jpg:large">
				<figcaption><a href="#">@analog_cafe</a>: "The meaning of life is to find your gift. The purpose of life is to give it away.”  ― Pablo Picasso</figcaption>
			</figure>
			<a href="#" class="button">View on Twitter</a>
		</aside>
		<p>Most of the time things work just fine. We see stuff, the brain makes sense out of it; how it moves and changes over time. Occasionally, nothing is there, neither does it move. A video that you watch on YouTube isn't real. It's just millions of tiny light bulbs changing color as dictated by the computer. Everything is static, except for the intensity of light and the wavelength for each pixel.</p>
		<blockquote><p>We think something is in motion when it's moving along the vertical or horisontal axis. It could swing like a pendulum or it could move in a single direction.</p></blockquote>
		<p>We think something is in motion when it changes ten times per second or faster. What happens to it within each one of those moments is crucial as it adds to our idea of where it moves or how it changes.</p>
		<blockquote><p>We think something is in motion when it's moving along the vertical or horisontal axis. It could swing like a pendulum or it could move in a single direction. We think something is in motion when it's moving along the vertical or horisontal axis. It could swing like a pendulum or it could move in a single direction.</p><p>We think something is in motion when it's moving along the vertical or horisontal axis. It could swing like a pendulum or it could move in a single direction.</p><cite>A quote by some famous guy.</cite></blockquote>
		<p>The first time we tricked our brains like that was over <a href="https://en.wikipedia.org/wiki/History_of_animation#Early_approaches_to_motion_in_art">5,000 years ago</a>. We never stopped since. Animation has been with us through time as we told stories and brought them to life through sound, written word, and images.</p>
		<figure class="feature">
			<%= image_tag "template/L_Very-Red-Flower.jpg" %>
			<figcaption>This is not a pipe" is a famous play on reality by René Magritte. He was trying to say that the image he drew and most would refer to as a "pipe" isn't. It's just a drawing or a collection of color pigments on a piece of paper. Can't smoke that.</figcaption>
		</figure>
		<figure class="feature">
			<%= image_tag "template/L_Let-It-Go.jpg" %>
			<figcaption>This is not a pipe" is a famous play on reality by René Magritte. He was trying to say that the image he drew and most would refer to as a "pipe" isn't. It's just a drawing or a collection of color pigments on a piece of paper. Can't smoke that.</figcaption>
		</figure>
		<figure class="feature">
			<%= image_tag "template/L_Woop-Woop.jpg" %>
			<figcaption>This is not a pipe" is a famous play on reality by René Magritte. He was trying to say that the image he drew and most would refer to as a "pipe" isn't. It's just a drawing or a collection of color pigments on a piece of paper. Can't smoke that.</figcaption>
		</figure>
		<figure class="feature">
			<%= image_tag "template/11.6.2016-de.jpg" %>
			<figcaption>This is not a pipe" is a famous play on reality by René Magritte. He was trying to say that the image he drew and most would refer to as a "pipe" isn't. It's just a drawing or a collection of color pigments on a piece of paper. Can't smoke that.</figcaption>
		</figure>
		<aside class="card">
			<header>
				<h3>Section Card</h3>
				<a href="#">&#10005;</a>
			</header>
			<figure>
				<%= image_tag "template/L_Let-It-Go.jpg" %>
				<figcaption>This is a card. It contains additional info, options & contextual menus.</figcaption>
			</figure>
			<a href="#" class="button">Section Card Button</a>
		</aside>
		<a href="#" class="button">Section Button</a>
	</section>
	<a href="#" class="button">Article Button</a>
</article>
<a href="#" class="button">Main Button</a>
<aside class="card" style="position: absolute; top: 1040px; left: calc(50% - 160px);">
	<header>
		<h3>Main Card</h3>
		<a href="#">&#10005;</a>
	</header>
	<figure>
		<%= image_tag "template/L_Let-It-Go.jpg" %>
		<figcaption>This is a card. It contains additional info, options & contextual menus.</figcaption>
	</figure>
	<a href="#" class="button">Main Card Button</a>
</aside>

app/views/template/articles.html.erb
<% @document_title="Articles" %>

<section class="motto"><span><q><em>Featured stories and articles</em></q> &#x1F4D6;</span></section>
<a href="#" class="tools"></a>

<div class="header-bleed">
	<%= render "shared/table-of-contents" %>
	<a href="#" class="button">Load More...</a>
</div>

app/views/template/essays.html.erb
<% @document_title="Photo Essays" %>

<section class="motto"><span><q><em>Curated photo essays and photography</em></q> &#x1F391;</span></section>
<a href="#" class="tools"></a>

<div class="header-bleed">
	<%= render "shared/table-of-contents" %>
	<a href="#" class="button">Load More...</a>
</div>

app/views/template/favorites.erb
<% @document_title="Home" %>

<section class="motto"><span><q><em>Your beloved Analog.Cafe stuff lives here</em></q> &#x1F60D;</span></section>

<!-- 
<a href="#" class="tools"></a>
 -->

<div class="header-bleed">
	<%= render "shared/table-of-contents" %>
	<a href="#" class="button">Load More...</a>
</div>

app/views/template/favorites.html.erb
<% @document_title="Favorites" %>

<section class="motto"><span><q><em>Your favorites live here</em></q> &#x1F60D;</span></section>

<!-- 
<a href="#" class="tools"></a>
 -->

<div class="header-bleed">
	<%= render "shared/table-of-contents" %>
	<a href="#" class="button">Load More...</a>
</div>

app/views/template/index.html.erb
<section class="motto"><span><q><em>The <%= link_to 'remarkable', remarkable_path %> film photo blog</em></q> &#x1F60C;</span></section>
<a href="#" class="tools"></a>

<div class="header-bleed">
	<%= render "shared/table-of-contents" %>
	<a href="#" class="button">Load More...</a>
</div>

app/views/template/submit.html.erb
<% @document_title="Submit" %>

<article>
	<header>
		<h1>Submit</h1>
		<span class="subtitle">Have your film photography, prose and articles featured on Analog.Cafe!</span>
		<span class="small-caption">Written by <a href="#">dmitrizzle</a> &middot; January 30, 2017</span>
		<div class="controls"><a href="#" class="tools"></a></div>
	</header>
	<section>
		<h2>For The Creators:</h2>
		<p>Analog.Cafe is more than just a blog. It is the <strong>ultimate publishing platform for the film photography community</strong>.</p>
		<blockquote><p>Anyone can submit images, photo essays and articles through the beautiful, easy to use web app. Featured images are listed in a special database. From there they can be re-published by others. This... facilitates <strong>effortless collaboration</strong>.</p></blockquote>
		<p><em>Analog.Cafe</em> is a collection of images, articles and photo essays. It is a fully curated and edited body of work that draws on the best and most interesting expressions from the film photography community and beyond.</p>
</article>